config/routes.rb
Rails.application.routes.draw do
  resources :pdfs
  resources :imagepieces
  resources :imageboards
  resources :attachments
  resources :boardgames

  root "boardgames#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pdf.rb
class Pdf < ApplicationRecord
  has_many :attachments, as: :attachable
  has_many_attached :rules
end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController
  before_action :set_pdf, only: %i[ show edit update destroy ]

  # GET /pdfs or /pdfs.json
  def index
    @pdfs = Pdf.all
  end

  # GET /pdfs/1 or /pdfs/1.json
  def show
  end

  # GET /pdfs/new
  def new
    @pdf = Pdf.new
  end

  # GET /pdfs/1/edit
  def edit
  end

  # POST /pdfs or /pdfs.json
  def create
    @pdf = Pdf.new(pdf_params)

    respond_to do |format|
      if @pdf.save
        format.html { redirect_to pdf_url(@pdf), notice: "Pdf was successfully created." }
        format.json { render :show, status: :created, location: @pdf }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pdfs/1 or /pdfs/1.json
  def update
    respond_to do |format|
      if @pdf.update(pdf_params)
        format.html { redirect_to pdf_url(@pdf), notice: "Pdf was successfully updated." }
        format.json { render :show, status: :ok, location: @pdf }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pdfs/1 or /pdfs/1.json
  def destroy
    @pdf.destroy

    respond_to do |format|
      format.html { redirect_to pdfs_url, notice: "Pdf was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pdf
      @pdf = Pdf.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pdf_params
      params.require(:pdf).permit(:name, rules: [])
    end
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/views/pdfs/_form.html.erb
<%= form_with(model: pdf, local: true) do |form| %>
  <% if pdf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pdf.errors.count, "error") %> prohibited this pdf from being saved:</h2>

      <ul>
      <% pdf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :rules%>
    <%= form.file_field :rules, multiple: true%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pdfs/edit.html.erb
<h1>Editing Pdf</h1>

<%= render 'form', pdf: @pdf %>

<%= link_to 'Show', @pdf %> |
<%= link_to 'Back', pdfs_path %>

app/views/pdfs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pdfs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pdfs.each do |pdf| %>
      <tr>
        <td><%= pdf.name %></td>
        <td><%= link_to 'Show', pdf %></td>
        <td><%= link_to 'Edit', edit_pdf_path(pdf) %></td>
        <td><%= link_to 'Destroy', pdf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pdf', new_pdf_path %>

app/views/pdfs/new.html.erb
<h1>New Pdf</h1>

<%= render 'form', pdf: @pdf %>

<%= link_to 'Back', pdfs_path %>

app/views/pdfs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pdf.name %>
</p>

<%= link_to 'Edit', edit_pdf_path(@pdf) %> |
<%= link_to 'Back', pdfs_path %>