config/routes.rb
Rails.application.routes.draw do
  resources :pdfs
  resources :imagepieces
  resources :imageboards
  resources :attachments
  resources :boardgames

  root "boardgames#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/imagepiece.rb
class Imagepiece < ApplicationRecord
  has_many :attachments, as: :attachable
  has_many_attached :img_pieces
end
  

app/controllers/imagepieces_controller.rb
class ImagepiecesController < ApplicationController
  before_action :set_imagepiece, only: %i[ show edit update destroy ]

  # GET /imagepieces or /imagepieces.json
  def index
    @imagepieces = Imagepiece.all
  end

  # GET /imagepieces/1 or /imagepieces/1.json
  def show
  end

  # GET /imagepieces/new
  def new
    @imagepiece = Imagepiece.new
  end

  # GET /imagepieces/1/edit
  def edit
  end

  # POST /imagepieces or /imagepieces.json
  def create
    @imagepiece = Imagepiece.new(imagepiece_params)

    respond_to do |format|
      if @imagepiece.save
        format.html { redirect_to imagepiece_url(@imagepiece), notice: "Imagepiece was successfully created." }
        format.json { render :show, status: :created, location: @imagepiece }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @imagepiece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imagepieces/1 or /imagepieces/1.json
  def update
    respond_to do |format|
      if @imagepiece.update(imagepiece_params)
        format.html { redirect_to imagepiece_url(@imagepiece), notice: "Imagepiece was successfully updated." }
        format.json { render :show, status: :ok, location: @imagepiece }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @imagepiece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imagepieces/1 or /imagepieces/1.json
  def destroy
    @imagepiece.destroy

    respond_to do |format|
      format.html { redirect_to imagepieces_url, notice: "Imagepiece was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imagepiece
      @imagepiece = Imagepiece.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def imagepiece_params
      params.require(:imagepiece).permit(:name, img_pieces: [])
    end
end

app/helpers/imagepieces_helper.rb
module ImagepiecesHelper
end

app/views/imagepieces/_form.html.erb
<%= form_with(model: imagepiece, local: true) do |form| %>
  <% if imagepiece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(imagepiece.errors.count, "error") %> prohibited this imagepiece from being saved:</h2>

      <ul>
      <% imagepiece.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :img_board%>
    <%= form.file_field :img_pieces, multiple: true%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/imagepieces/edit.html.erb
<h1>Editing Imagepiece</h1>

<%= render 'form', imagepiece: @imagepiece %>

<%= link_to 'Show', @imagepiece %> |
<%= link_to 'Back', imagepieces_path %>

app/views/imagepieces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Imagepieces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @imagepieces.each do |imagepiece| %>
      <tr>
        <td><%= imagepiece.name %></td>
        <td><%= link_to 'Show', imagepiece %></td>
        <td><%= link_to 'Edit', edit_imagepiece_path(imagepiece) %></td>
        <td><%= link_to 'Destroy', imagepiece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Imagepiece', new_imagepiece_path %>

app/views/imagepieces/new.html.erb
<h1>New Imagepiece</h1>

<%= render 'form', imagepiece: @imagepiece %>

<%= link_to 'Back', imagepieces_path %>

app/views/imagepieces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @imagepiece.name %>
</p>

<%= link_to 'Edit', edit_imagepiece_path(@imagepiece) %> |
<%= link_to 'Back', imagepieces_path %>