config/routes.rb
Rails.application.routes.draw do
  resources :pdfs
  resources :imagepieces
  resources :imageboards
  resources :attachments
  resources :boardgames

  root "boardgames#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/boardgame.rb
class Boardgame < ApplicationRecord
  has_many :attachment_boardgames
  has_many :attachments, through: :attachment_boardgames
end

app/controllers/boardgames_controller.rb
class BoardgamesController < ApplicationController
  before_action :set_boardgame, only: %i[ show edit update destroy ]

  # GET /boardgames or /boardgames.json
  def index
    @boardgames = Boardgame.all
    @attachments = Attachment.all
  end

  # GET /boardgames/1 or /boardgames/1.json
  def show
  end

  # GET /boardgames/new
  def new
    @boardgame = Boardgame.new
  end

  # GET /boardgames/1/edit
  def edit
  end

  # POST /boardgames or /boardgames.json
  def create
    @boardgame = Boardgame.new(boardgame_params)

    respond_to do |format|
      if @boardgame.save
        format.html { redirect_to boardgame_url(@boardgame), notice: "Boardgame was successfully created." }
        format.json { render :show, status: :created, location: @boardgame }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @boardgame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boardgames/1 or /boardgames/1.json
  def update
    respond_to do |format|
      if @boardgame.update(boardgame_params)
        format.html { redirect_to boardgame_url(@boardgame), notice: "Boardgame was successfully updated." }
        format.json { render :show, status: :ok, location: @boardgame }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @boardgame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boardgames/1 or /boardgames/1.json
  def destroy
    @boardgame.destroy

    respond_to do |format|
      format.html { redirect_to boardgames_url, notice: "Boardgame was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boardgame
      @boardgame = Boardgame.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def boardgame_params
      params.require(:boardgame).permit(:name, :min_players, :max_players, :description, :ages)
    end
end

app/helpers/boardgames_helper.rb
module BoardgamesHelper
end

app/views/boardgames/_form.html.erb
<%= form_with(model: boardgame, local: true) do |form| %>
  <% if boardgame.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boardgame.errors.count, "error") %> prohibited this boardgame from being saved:</h2>

      <ul>
      <% boardgame.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :min_players %>
    <%= form.number_field :min_players %>
  </div>

  <div class="field">
    <%= form.label :max_players %>
    <%= form.number_field :max_players %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :ages %>
    <%= form.text_field :ages %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boardgames/edit.html.erb
<h1>Editing Boardgame</h1>

<%= render 'form', boardgame: @boardgame %>

<%= link_to 'Show', @boardgame %> |
<%= link_to 'Back', boardgames_path %>

app/views/boardgames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boardgames</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Min players</th>
      <th>Max players</th>
      <th>Description</th>
      <th>Ages</th>
      <th>Boardgame Pic</th>
      <th>Pieces Images</th>
      <th>Rules</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boardgames.each do |boardgame| %>
      <tr>
        <td><%= boardgame.name %></td>
        <td><%= boardgame.min_players %></td>
        <td><%= boardgame.max_players %></td>
        <td><%= boardgame.description %></td>
        <td><%= boardgame.ages %></td>
        <%# TODO %>
        <td><%= boardgame.attachments %></td>
        <td><%= boardgame.ages %></td>
        <td><%= boardgame.ages %></td>
        <td><%= link_to 'Show', boardgame %></td>
        <td><%= link_to 'Edit', edit_boardgame_path(boardgame) %></td>
        <td><%= link_to 'Destroy', boardgame, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boardgame', new_boardgame_path %>

app/views/boardgames/new.html.erb
<h1>New Boardgame</h1>

<%= render 'form', boardgame: @boardgame %>

<%= link_to 'Back', boardgames_path %>

app/views/boardgames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @boardgame.name %>
</p>

<p>
  <strong>Min players:</strong>
  <%= @boardgame.min_players %>
</p>

<p>
  <strong>Max players:</strong>
  <%= @boardgame.max_players %>
</p>

<p>
  <strong>Description:</strong>
  <%= @boardgame.description %>
</p>

<p>
  <strong>Ages:</strong>
  <%= @boardgame.ages %>
</p>

<%= link_to 'Edit', edit_boardgame_path(@boardgame) %> |
<%= link_to 'Back', boardgames_path %>